* Exercise 1

Give an example of a 2x2 game with no dominating strategy for either player.

** Solution

It suffices to have different best responses for each one of each players' moves.

|   | A       | B       |
|---+---------+---------|
| A | (0,  0) | (2, -1) |
| B | (1, -1) | (1,  1) |

Here P1 is the row player. 

If P1 plays A, P2's best response is A
If P1 plays B, P2's best response is B
If P2 plays A, P1's best response is B.
If P2 plays B, P1's best response is A.

* Exercise 2

P2 needs P1's help to play a game. If they win the game, they get 100 CHF, and P2 promises to give some % of the winnings. P1 can accept or decline. 

P2's utility is the amount of money won.

P1's utility is the amount of money given by P2, plus plus a constant c, which encodes either:
(a) some intrinsic reward he obtains, if c > 0
(b) some cost he has to incur to play, if c < 0.

Of course, if they lose, then P2 obtains a utility of 0, while P1 obtains c.

Assuming each player cares about maximising expected utility, and that the winning probability is 50%, what is the optimal strategy for the each player, assuming P2 commits first, and then P1 accepts or declines? For simplicity, you can consider that P2 makes offers of 0, 25, 50, 75, or 100%.

** Solution

It helps to write out a table for all possible outcomes.
|-----------------+----------+------------+------------+------------+--------------|
|                 | 0%       | 25%        | 50%        | 75%        | 100%         |
|-----------------+----------+------------+------------+------------+--------------|
| Decline         | (0, 0)   | (0,0)      | (0,0)      | (0,0)      | (0,0)        |
|-----------------+----------+------------+------------+------------+--------------|
| Accept and win  | (100, c) | (75, 25+c) | (50, 50+c) | (25, 75+c) | (0, 100 + c) |
| Accept and lose | (0, c)   | (0, 0+c)   | (50, 50+c) | (25, 75+c) | (0, 100 + c) |
|-----------------+----------+------------+------------+------------+--------------|

Since the probability of winning is 50%, we can write the expected utility for each case.
|---------+---------+----------------+------------+----------------+-------------|
|         | 0%      | 25%            | 50%        | 75%            | 100%        |
|---------+---------+----------------+------------+----------------+-------------|
| Decline | (0, 0)  | (0,0)          | (0,0)      | (0,0)          | (0,0)       |
|---------+---------+----------------+------------+----------------+-------------|
| Accept  | (50, c) | (37.5, 12.5+c) | (25, 25+c) | (12.5, 37.5+c) | (0, 50 + c) |
|---------+---------+----------------+------------+----------------+-------------|

If $c > 0$, then P1 always accepts. If $p$ is the probability of winning and $R$ is the ratio of winnings given, then P1 accepts only when  $c > - p * R * 100$.

For that reason, it is optimal for P2 to offer exactly $R = - c / (100 p)$ 

* Exercise 3

As a reminder, a pure Nash equlibrium is a choice of actions $a$ so that
\[
\rho_i(a) \geq \rho_i(a'_i, a_{-i})
\]
Does this game, where P1 is the row player, have a pure Nash equilibrium? 
If so, identify it. 


|   | 1     | 2     | 3     |
|---+-------+-------+-------|
| 1 | (0,0) | (1,2) | (1,3) |
| 2 | (5,0) | (0,0) | (2,1) |
| 3 | (3,1) | (2,1) | (0,0) |

** Solution

If the players play $a = (3,2)$ then they obtain $(2,1)$. If P1 deviates from this, he obtains either 0 or 1 instead of 2. If P2 deviates, he obtains either 1 or 0, instead of 0. So
$\rho_i(a) \geq \rho_i(a, -i)$.

* Exercise 4

Consider the following alternating minimax game, i.e. where each player moves in term.
At the first stage, P1 moves, then P2 moves, and then the game ends.

